directories:
    data: data
    db: mock_db

prediction:
    pipeline: baseline
    data: 
    run_id_training: 
    checkpoint:
    directories:
        prefix: data
    num_workers: 8
    log_metrics: False
    torch:
        device: 0
