defaults:
    - model: unet
    - train: unet
    - validate: unet
    - logging: wandb
    - ddp: ddp
    - runs: runs
    - inputs: inputs
    - inference: unet
    - _self_

seed: 42
device: cuda

model_type: "UNet"
loss_type: "cross_entropy_scaling"

data:
    voxel_size: [5, 5, 5]
    downsample_factor: 1
    num_classes: 2

base: /nfs/scratch/ajain
incasem_dir: ${base}/incasem

directories:
    runs: ${incasem_dir}/runs 
    data: ${incasem_dir}/incasem/data

training_runs:
    continue_id: null
    run_id: null