pipeline: baseline_with_context
data: "/nfs/scratch/ajain/incasem/scripts/02_train/data_configs/example_validation_er.json"
validate_every: 1000
input_size_voxels: [204, 204, 204]
output_size_voxels: [110, 110, 110]
snapshot:
    every: 10
