pipeline: baseline_with_context
data:  "/nfs/scratch/ajain/incasem/scripts/02_train/data_configs/example_train_er.json"
iterations: 200000
input_size_voxels: [204, 204, 204]
output_size_voxels: [110, 110, 110]
save_every: 1000
log_every: 1
optimizer:
    lr: 0.00003
    weight_decay: 0.00003
reject:
    min_masked: 0.05
    reject_probability: 0.9
augmentation:
    elastic:
        control_point_spacing: [32, 32, 32]
        jitter_sigma: [2, 2, 2]
        subsample: 4
    intensity:
        scale: 0.15
        shift: 0.15
    simple:
        transpose_only: [0, 1, 2]
snapshot:
    every: 1000
profiling_stats:
    every: 1000
precache:
    cache_size: 20
    num_workers: 8
resume: True
checkpointing:
    continue_run: ${training_runs.continue_id}
    resume_checkpoint: ${training_runs.run_id}
start_from: 0